In [1]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4,5] , dtype=np.int32)

In [4]:
print(arr)

[1 2 3 4 5]


In [7]:
print(arr.dtype)

int32


In [8]:
arr[0]=10
print(arr)

[10  2  3  4  5]


In [10]:
print(arr[0:3])

[10  2  3]


In [11]:
arr.shape

(5,)

In [15]:
arr_2=np.array([[1,2,3],
       [2,4,6]])
print(arr_2.shape)

(2, 3)


In [17]:
arr_3d = np.array([[[1,2,3],
                    [2,4,5]],
                  ])
print(arr_3d.shape)

(1, 2, 3)


a=np.array([1,2])

In [23]:
arr_3d.ndim

3

In [24]:
arr_2.ndim

2

In [25]:
arr.ndim

1

In [26]:
arr.size

5

In [27]:
arr_3d.size

6

In [28]:
arr_3d1=arr_3d.reshape(3,2)
print(arr_3d1)

[[1 2]
 [3 2]
 [4 5]]


In [29]:
print(arr_3d.reshape(3,2))

[[1 2]
 [3 2]
 [4 5]]


In [30]:
arr_3d.T

array([[[1],
        [2]],

       [[2],
        [4]],

       [[3],
        [5]]])

In [31]:
arr_2

array([[1, 2, 3],
       [2, 4, 6]])

In [32]:
arr_2.T

array([[1, 2],
       [2, 4],
       [3, 6]])

In [35]:
#empty matrix
a=np.empty((2,2))
print(a)

[[2.12199579e-314 1.41749319e-311]
 [7.68766145e-321 1.41749319e-311]]


In [42]:
a=np.eye(6,4)

In [43]:
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
#Sorting
a=np.array([5,4,23])
x=np.argsort(a)
print(x)

[1 0 2]


In [50]:
#Concatenation
c=np.concatenate((a,x))
print(c)

[ 5  4 23  1  0  2]


In [58]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[0,0]])

In [59]:
z=np.concatenate((x,y),axis=1)

In [60]:
print(z)

[[1 2 5 6]
 [3 4 0 0]]


In [62]:
a=np.array([[1,2,3],[2,3,4]])
print(a.shape)

(2, 3)


In [67]:
ac=a[np.newaxis,::]

In [68]:
print(ac.shape)

(1, 2, 3)


In [69]:
print(ac)

[[[1 2 3]
  [2 3 4]]]


In [2]:
a=np.array([[1,2,3],[2,3,4]])

In [3]:
sum=np.sum(a)
print(sum)

15


In [4]:
print(a)

[[1 2 3]
 [2 3 4]]


In [5]:
print(np.sum(a,axis=0))

[3 5 7]


In [6]:
print(np.sum(a,axis=1))

[6 9]


In [7]:
b=np.max(a)

In [8]:
print(b)

4


In [10]:
print(np.max(a , axis=1))

[3 4]


In [12]:
#Matrix operations
list=[1 ,2, 3, 4]
array=np.array([1,2,3,4])

In [13]:
a=list*2
b=array*2
print(a)
print(b)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
arr=np.array([1,2,3,3,3,4,5,1,5,6,4,6])

In [23]:
unique , occur=np.unique(arr , return_counts=True)
print(unique)
print(occur)

[1 2 3 4 5 6]
[2 1 3 2 2 2]


In [28]:
a=np.array([[1,2,3],[1,4,3]])
print(a.shape)

(2, 3)


In [29]:
b=np.unique(a , axis=0)
print(b)

[[1 2 3]
 [1 4 3]]


In [30]:
arr=np.array([1,2,3,4])
print(np.flip(arr))

[4 3 2 1]


In [38]:
arr=np.array([[1,2,3,4],[4,3,4,3],[1,7,5,4]])
print(arr)
print(np.flip(arr,axis=1))

[[1 2 3 4]
 [4 3 4 3]
 [1 7 5 4]]
[[4 3 2 1]
 [3 4 3 4]
 [4 5 7 1]]


In [39]:
print(arr.flatten())

[1 2 3 4 4 3 4 3 1 7 5 4]
